#!/bin/bash
#

function publish_to_registry {
	local TOP_DIR="$(cd "$(dirname "$0")"/../ && pwd)"
	local PACKAGE_JSON_LN="${TOP_DIR}/package.ls"
	local PACKAGE_JSON="${TOP_DIR}/package.json"
	local VERSION=$(cat ${TOP_DIR}/CHANGELOG.md | grep '^###' | head -n1 | awk '{print $2}')
	local NAME=$(cat ${PACKAGE_JSON} | jq -r ".name")
	echo "generating ${PACKAGE_JSON} ..." && \
		cat ${PACKAGE_JSON_LN} | lsc -cjp | jq ".version=\"${VERSION}\"" > ${PACKAGE_JSON} && \
		echo "unpublish ${NAME}@${VERSION} ..." && npm unpublish ${NAME}@${VERSION} && \
		echo "waiting for 5 seconds ..." && sleep 5 && \
		npm publish --scope public
}

publish_to_registry $@
